name: sigma
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
dependencies:
  - ca-certificates=2021.5.30=h5b45459_0
  - openssl=1.1.1l=h8ffe710_0
  - pip=21.2.4=pyhd8ed1ab_0
  - python=3.7.10=h7840368_100_cpython
  - python_abi=3.7=2_cp37m
  - setuptools=58.0.4=py37h03978a9_0
  - sqlite=3.36.0=h8ffe710_1
  - ucrt=10.0.20348.0=h57928b3_0
  - vc=14.2=hb210afc_5
  - vs2015_runtime=14.29.30037=h902a5da_5
  - wheel=0.37.0=pyhd8ed1ab_1
  - pip:
    - absl-py==0.13.0
    - anyio==3.3.1
    - argcomplete==1.12.3
    - argon2-cffi==21.1.0
    - astunparse==1.6.3
    - attrs==21.2.0
    - babel==2.9.1
    - backcall==0.2.0
    - bleach==4.1.0
    - cached-property==1.5.2
    - cachetools==4.2.2
    - certifi==2021.5.30
    - cffi==1.14.6
    - charset-normalizer==2.0.4
    - clang==5.0
    - colorama==0.4.4
    - debugpy==1.4.3
    - decorator==5.1.0
    - defusedxml==0.7.1
    - entrypoints==0.3
    - flatbuffers==1.12
    - gast==0.4.0
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.40.0
    - h5py==3.1.0
    - idna==3.2
    - importlib-metadata==4.8.1
    - ipykernel==6.4.1
    - ipython==7.27.0
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - jinja2==3.0.1
    - joblib==1.0.1
    - json5==0.9.6
    - jsonschema==3.2.0
    - jupyter-client==7.0.2
    - jupyter-core==4.7.1
    - jupyter-server==1.11.0
    - jupyterlab==3.1.11
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.8.1
    - keras==2.6.0
    - keras-preprocessing==1.1.2
    - lxml==4.6.3
    - markdown==3.3.4
    - markupsafe==2.0.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - nbclassic==0.3.1
    - nbclient==0.5.4
    - nbconvert==6.1.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - networkx==2.6.3
    - notebook==6.4.3
    - numpy==1.19.5
    - oauthlib==3.1.1
    - opt-einsum==3.3.0
    - packaging==21.0
    - pandas==1.3.3
    - pandocfilters==1.4.3
    - parso==0.8.2
    - pickleshare==0.7.5
    - prometheus-client==0.11.0
    - prompt-toolkit==3.0.20
    - protobuf==3.17.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pygments==2.10.0
    - pyparsing==2.4.7
    - pyrsistent==0.18.0
    - python-dateutil==2.8.2
    - pytz==2021.1
    - pywin32==301
    - pywinpty==1.1.4
    - pyzmq==22.2.1
    - rdkit-pypi==2021.3.5.1
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - requests-unixsocket==0.2.0
    - rsa==4.7.2
    - scikit-learn==0.24.2
    - scipy==1.7.1
    - send2trash==1.8.0
    - six==1.15.0
    - sniffio==1.2.0
    - spektral==1.0.5
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.6.0
    - tensorflow-estimator==2.6.0
    - termcolor==1.1.0
    - terminado==0.12.1
    - testpath==0.5.0
    - threadpoolctl==2.2.0
    - tornado==6.1
    - tqdm==4.62.2
    - traitlets==5.1.0
    - typing-extensions==3.7.4.3
    - urllib3==1.26.6
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.2.1
    - werkzeug==2.0.1
    - wrapt==1.12.1
    - zipp==3.5.0
prefix: D:\anaconda\envs\sigma
